name: Docker Image CI

env:
  VERSION: "2.6.3"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +%s)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "my-image-name:$VERSION-${{ steps.date.outputs.timestamp }}"
