name: Docker Image CI

env:
  TAG: $(date +%s)
  VERSION: "2.6.3"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "my-image-name:$VERSION-$TAG"
